# Generated by Django 4.0.4 on 2023-06-10 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=80)),
                ('response', models.CharField(max_length=100)),
                ('disciplina', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.disciplina')),
            ],
        ),
    ]
